server:
  port: 8001

spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order-service-8001
    prefer-ip-address: true

info:
  app.name: wu-spring-cloud
  company.name: www.wuhaiwei.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$