server:
  port: 8001

spring:
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order-service-hystrix-8001
    prefer-ip-address: true